### PR TITLE
Keep language consistent - SDK > manager

### PR DESCRIPTION
**Pull request by esthersweon**

### CODE REVIEW

**Comment by amacneil** [comment]
Maybe ask for others input on this, but "manager" seems more appropriate to me than "sdk". I think of "sdk" as a library.

**Comment by jtbandes** [comment]
Should we just delete this line? It was copied from https://github.com/microsoft/vscode-vsce. We've made a lot of changes since then.

**Comment by esthersweon** [comment]
> Maybe ask for others input on this, but "manager" seems more appropriate to me than "sdk". I think of "sdk" as a library.

@defunctzombie - thoughts? Believe you preferred SDK when referring to foxglove/fox, from your comments on the extensions blog post. 

cc: @amacneil

**Comment by jhurliman** [comment]
I agree with @amacneil , this is an executable application not an SDK.

**Comment by defunctzombie** [comment]
LGTM

**Comment by esthersweon** [comment]
Keeping manager terminology.

**Pull request closed without merging**
